exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: mixed-line-ending

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 24.4.1
  hooks:
    - id: black

- repo: https://github.com/john-hen/Flake8-pyproject
  rev: 1.2.3
  hooks:
    - id: Flake8-pyproject

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      additional_dependencies: [Flake8-pyproject]

- repo: https://github.com/detailyang/pre-commit-shell
  rev: 1.0.5
  hooks:
    - id: shell-lint

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.8
  hooks:
    - id: bandit
      args: ['--exclude', 'tests']
